const mockUsers = [
  {
    id: 1,
    firstName: "Ardenia",
    lastName: "Wardington",
    email: "awardington0@samsung.com",
    age: 65,
    address: "Room 1567",
    avatarUrl: "http://dummyimage.com/191x100.png/dddddd/000000",
  },
  {
    id: 2,
    firstName: "Polly",
    lastName: "Petz",
    email: "ppetz1@apple.com",
    age: 18,
    address: "Suite 83",
    avatarUrl: "http://dummyimage.com/164x100.png/cc0000/ffffff",
  },
  {
    id: 3,
    firstName: "Josh",
    lastName: "Valsler",
    email: "jvalsler2@webeden.co.uk",
    age: 71,
    address: "Suite 94",
    avatarUrl: "http://dummyimage.com/104x100.png/ff4444/ffffff",
  },
  {
    id: 4,
    firstName: "Justina",
    lastName: "Drable",
    email: "jdrable3@boston.com",
    age: 45,
    address: "Suite 36",
    avatarUrl: "http://dummyimage.com/179x100.png/ff4444/ffffff",
  },
  {
    id: 5,
    firstName: "Alexandrina",
    lastName: "Leschelle",
    email: "aleschelle4@yolasite.com",
    age: 84,
    address: "PO Box 19104",
    avatarUrl: "http://dummyimage.com/176x100.png/5fa2dd/ffffff",
  },
  {
    id: 6,
    firstName: "Cathi",
    lastName: "Purselow",
    email: "cpurselow5@unblog.fr",
    age: 30,
    address: "Apt 1394",
    avatarUrl: "http://dummyimage.com/159x100.png/cc0000/ffffff",
  },
  {
    id: 7,
    firstName: "Raynor",
    lastName: "Caitlin",
    email: "rcaitlin6@boston.com",
    age: 88,
    address: "PO Box 32857",
    avatarUrl: "http://dummyimage.com/184x100.png/5fa2dd/ffffff",
  },
  {
    id: 8,
    firstName: "Eberhard",
    lastName: "Grogono",
    email: "egrogono7@usnews.com",
    age: 33,
    address: "8th Floor",
    avatarUrl: "http://dummyimage.com/142x100.png/dddddd/000000",
  },
  {
    id: 9,
    firstName: "Randene",
    lastName: "Walthall",
    email: "rwalthall8@pagesperso-orange.fr",
    age: 32,
    address: "18th Floor",
    avatarUrl: "http://dummyimage.com/220x100.png/dddddd/000000",
  },
  {
    id: 10,
    firstName: "Elliott",
    lastName: "Cassell",
    email: "ecassell9@e-recht24.de",
    age: 45,
    address: "7th Floor",
    avatarUrl: "http://dummyimage.com/222x100.png/cc0000/ffffff",
  },
  {
    id: 11,
    firstName: "Bertrando",
    lastName: "Decroix",
    email: "bdecroixa@yandex.ru",
    age: 32,
    address: "Apt 552",
    avatarUrl: "http://dummyimage.com/221x100.png/ff4444/ffffff",
  },
  {
    id: 12,
    firstName: "Edwin",
    lastName: "Nuzzi",
    email: "enuzzib@wisc.edu",
    age: 71,
    address: "Apt 362",
    avatarUrl: "http://dummyimage.com/174x100.png/cc0000/ffffff",
  },
  {
    id: 13,
    firstName: "Madel",
    lastName: "Nichol",
    email: "mnicholc@rakuten.co.jp",
    age: 91,
    address: "Room 411",
    avatarUrl: "http://dummyimage.com/181x100.png/dddddd/000000",
  },
  {
    id: 14,
    firstName: "Pavia",
    lastName: "Banat",
    email: "pbanatd@uol.com.br",
    age: 32,
    address: "8th Floor",
    avatarUrl: "http://dummyimage.com/160x100.png/ff4444/ffffff",
  },
  {
    id: 15,
    firstName: "Barnabe",
    lastName: "Barbie",
    email: "bbarbiee@yahoo.co.jp",
    age: 40,
    address: "Room 244",
    avatarUrl: "http://dummyimage.com/191x100.png/5fa2dd/ffffff",
  },
  {
    id: 16,
    firstName: "Jeffie",
    lastName: "Heys",
    email: "jheysf@symantec.com",
    age: 18,
    address: "3rd Floor",
    avatarUrl: "http://dummyimage.com/221x100.png/ff4444/ffffff",
  },
  {
    id: 17,
    firstName: "Di",
    lastName: "Baudet",
    email: "dbaudetg@biglobe.ne.jp",
    age: 97,
    address: "13th Floor",
    avatarUrl: "http://dummyimage.com/198x100.png/dddddd/000000",
  },
  {
    id: 18,
    firstName: "Veronike",
    lastName: "Martino",
    email: "vmartinoh@squarespace.com",
    age: 11,
    address: "Apt 10",
    avatarUrl: "http://dummyimage.com/245x100.png/dddddd/000000",
  },
  {
    id: 19,
    firstName: "Athene",
    lastName: "Hirtzmann",
    email: "ahirtzmanni@hatena.ne.jp",
    age: 72,
    address: "Suite 1",
    avatarUrl: "http://dummyimage.com/236x100.png/cc0000/ffffff",
  },
  {
    id: 20,
    firstName: "Ian",
    lastName: "Silveston",
    email: "isilvestonj@jalbum.net",
    age: 10,
    address: "Apt 128",
    avatarUrl: "http://dummyimage.com/201x100.png/ff4444/ffffff",
  },
  {
    id: 21,
    firstName: "Pearline",
    lastName: "Matthieson",
    email: "pmatthiesonk@printfriendly.com",
    age: 61,
    address: "Suite 37",
    avatarUrl: "http://dummyimage.com/159x100.png/ff4444/ffffff",
  },
  {
    id: 22,
    firstName: "Othella",
    lastName: "Maliffe",
    email: "omaliffel@google.co.jp",
    age: 20,
    address: "Apt 870",
    avatarUrl: "http://dummyimage.com/222x100.png/cc0000/ffffff",
  },
  {
    id: 23,
    firstName: "Jerrilyn",
    lastName: "Knightley",
    email: "jknightleym@goo.ne.jp",
    age: 30,
    address: "Room 315",
    avatarUrl: "http://dummyimage.com/139x100.png/dddddd/000000",
  },
  {
    id: 24,
    firstName: "Simeon",
    lastName: "Galey",
    email: "sgaleyn@infoseek.co.jp",
    age: 46,
    address: "Room 1233",
    avatarUrl: "http://dummyimage.com/182x100.png/dddddd/000000",
  },
  {
    id: 25,
    firstName: "Cecil",
    lastName: "Smallshaw",
    email: "csmallshawo@boston.com",
    age: 67,
    address: "Apt 705",
    avatarUrl: "http://dummyimage.com/152x100.png/dddddd/000000",
  },
  {
    id: 26,
    firstName: "Domenico",
    lastName: "Kniveton",
    email: "dknivetonp@goo.gl",
    age: 40,
    address: "Room 1068",
    avatarUrl: "http://dummyimage.com/249x100.png/dddddd/000000",
  },
  {
    id: 27,
    firstName: "Ronica",
    lastName: "Tamburi",
    email: "rtamburiq@squarespace.com",
    age: 74,
    address: "Apt 1969",
    avatarUrl: "http://dummyimage.com/192x100.png/ff4444/ffffff",
  },
  {
    id: 28,
    firstName: "Olga",
    lastName: "Shepperd",
    email: "oshepperdr@ftc.gov",
    age: 94,
    address: "6th Floor",
    avatarUrl: "http://dummyimage.com/233x100.png/dddddd/000000",
  },
  {
    id: 29,
    firstName: "Domenic",
    lastName: "Marriot",
    email: "dmarriots@yelp.com",
    age: 75,
    address: "PO Box 26857",
    avatarUrl: "http://dummyimage.com/107x100.png/ff4444/ffffff",
  },
  {
    id: 30,
    firstName: "Allister",
    lastName: "Deverille",
    email: "adeverillet@edublogs.org",
    age: 39,
    address: "14th Floor",
    avatarUrl: "http://dummyimage.com/163x100.png/cc0000/ffffff",
  },
  {
    id: 31,
    firstName: "Dolli",
    lastName: "Tapley",
    email: "dtapleyu@ucsd.edu",
    age: 46,
    address: "Suite 68",
    avatarUrl: "http://dummyimage.com/226x100.png/ff4444/ffffff",
  },
  {
    id: 32,
    firstName: "Ardys",
    lastName: "Gravey",
    email: "agraveyv@deliciousdays.com",
    age: 93,
    address: "Room 829",
    avatarUrl: "http://dummyimage.com/190x100.png/ff4444/ffffff",
  },
  {
    id: 33,
    firstName: "Brand",
    lastName: "Heningam",
    email: "bheningamw@bbc.co.uk",
    age: 90,
    address: "Suite 90",
    avatarUrl: "http://dummyimage.com/229x100.png/5fa2dd/ffffff",
  },
  {
    id: 34,
    firstName: "Peterus",
    lastName: "Wagstaff",
    email: "pwagstaffx@cnbc.com",
    age: 95,
    address: "9th Floor",
    avatarUrl: "http://dummyimage.com/224x100.png/5fa2dd/ffffff",
  },
  {
    id: 35,
    firstName: "Coral",
    lastName: "Scrange",
    email: "cscrangey@msn.com",
    age: 22,
    address: "Room 801",
    avatarUrl: "http://dummyimage.com/122x100.png/5fa2dd/ffffff",
  },
  {
    id: 36,
    firstName: "Shannon",
    lastName: "Beeston",
    email: "sbeestonz@is.gd",
    age: 60,
    address: "PO Box 64349",
    avatarUrl: "http://dummyimage.com/163x100.png/cc0000/ffffff",
  },
  {
    id: 37,
    firstName: "Fidelio",
    lastName: "Skill",
    email: "fskill10@hibu.com",
    age: 40,
    address: "Apt 572",
    avatarUrl: "http://dummyimage.com/169x100.png/ff4444/ffffff",
  },
  {
    id: 38,
    firstName: "Heath",
    lastName: "Sammonds",
    email: "hsammonds11@geocities.com",
    age: 40,
    address: "PO Box 21102",
    avatarUrl: "http://dummyimage.com/161x100.png/dddddd/000000",
  },
  {
    id: 39,
    firstName: "Lynea",
    lastName: "Kenen",
    email: "lkenen12@archive.org",
    age: 56,
    address: "Room 1656",
    avatarUrl: "http://dummyimage.com/163x100.png/5fa2dd/ffffff",
  },
  {
    id: 40,
    firstName: "Domingo",
    lastName: "Adamson",
    email: "dadamson13@forbes.com",
    age: 11,
    address: "PO Box 79212",
    avatarUrl: "http://dummyimage.com/197x100.png/ff4444/ffffff",
  },
  {
    id: 41,
    firstName: "Cathrin",
    lastName: "Ashton",
    email: "cashton14@163.com",
    age: 89,
    address: "PO Box 67479",
    avatarUrl: "http://dummyimage.com/150x100.png/5fa2dd/ffffff",
  },
  {
    id: 42,
    firstName: "Herschel",
    lastName: "Mc Dermid",
    email: "hmcdermid15@shutterfly.com",
    age: 24,
    address: "PO Box 37895",
    avatarUrl: "http://dummyimage.com/185x100.png/dddddd/000000",
  },
  {
    id: 43,
    firstName: "Efrem",
    lastName: "Hounihan",
    email: "ehounihan16@networksolutions.com",
    age: 22,
    address: "Room 990",
    avatarUrl: "http://dummyimage.com/250x100.png/ff4444/ffffff",
  },
  {
    id: 44,
    firstName: "Shane",
    lastName: "Wolver",
    email: "swolver17@domainmarket.com",
    age: 20,
    address: "Apt 1849",
    avatarUrl: "http://dummyimage.com/228x100.png/5fa2dd/ffffff",
  },
  {
    id: 45,
    firstName: "Clem",
    lastName: "Howson",
    email: "chowson18@tinypic.com",
    age: 80,
    address: "PO Box 55568",
    avatarUrl: "http://dummyimage.com/119x100.png/dddddd/000000",
  },
  {
    id: 46,
    firstName: "Carline",
    lastName: "Blackmuir",
    email: "cblackmuir19@pinterest.com",
    age: 92,
    address: "Room 497",
    avatarUrl: "http://dummyimage.com/185x100.png/ff4444/ffffff",
  },
  {
    id: 47,
    firstName: "Marten",
    lastName: "Husband",
    email: "mhusband1a@europa.eu",
    age: 96,
    address: "Room 82",
    avatarUrl: "http://dummyimage.com/138x100.png/dddddd/000000",
  },
  {
    id: 48,
    firstName: "Eleonora",
    lastName: "Croote",
    email: "ecroote1b@yale.edu",
    age: 31,
    address: "Apt 983",
    avatarUrl: "http://dummyimage.com/132x100.png/cc0000/ffffff",
  },
  {
    id: 49,
    firstName: "Ashely",
    lastName: "Scotti",
    email: "ascotti1c@go.com",
    age: 98,
    address: "PO Box 43851",
    avatarUrl: "http://dummyimage.com/250x100.png/dddddd/000000",
  },
  {
    id: 50,
    firstName: "Zonnya",
    lastName: "Postan",
    email: "zpostan1d@ycombinator.com",
    age: 50,
    address: "3rd Floor",
    avatarUrl: "http://dummyimage.com/203x100.png/ff4444/ffffff",
  },
  {
    id: 51,
    firstName: "Salomo",
    lastName: "Hintze",
    email: "shintze1e@sitemeter.com",
    age: 51,
    address: "Apt 1756",
    avatarUrl: "http://dummyimage.com/186x100.png/ff4444/ffffff",
  },
  {
    id: 52,
    firstName: "Cyndie",
    lastName: "Rape",
    email: "crape1f@google.com",
    age: 72,
    address: "Room 437",
    avatarUrl: "http://dummyimage.com/190x100.png/ff4444/ffffff",
  },
  {
    id: 53,
    firstName: "Hilliary",
    lastName: "Essam",
    email: "hessam1g@shinystat.com",
    age: 20,
    address: "11th Floor",
    avatarUrl: "http://dummyimage.com/242x100.png/cc0000/ffffff",
  },
  {
    id: 54,
    firstName: "Jermaine",
    lastName: "Cuttles",
    email: "jcuttles1h@hibu.com",
    age: 83,
    address: "Room 1286",
    avatarUrl: "http://dummyimage.com/182x100.png/cc0000/ffffff",
  },
  {
    id: 55,
    firstName: "Donia",
    lastName: "Charpling",
    email: "dcharpling1i@skype.com",
    age: 85,
    address: "Suite 97",
    avatarUrl: "http://dummyimage.com/242x100.png/ff4444/ffffff",
  },
  {
    id: 56,
    firstName: "Jandy",
    lastName: "Boissieux",
    email: "jboissieux1j@over-blog.com",
    age: 50,
    address: "Suite 8",
    avatarUrl: "http://dummyimage.com/230x100.png/5fa2dd/ffffff",
  },
  {
    id: 57,
    firstName: "Shane",
    lastName: "O'Hanlon",
    email: "sohanlon1k@nsw.gov.au",
    age: 15,
    address: "Apt 763",
    avatarUrl: "http://dummyimage.com/115x100.png/5fa2dd/ffffff",
  },
  {
    id: 58,
    firstName: "Terrel",
    lastName: "Garbar",
    email: "tgarbar1l@newyorker.com",
    age: 69,
    address: "Suite 50",
    avatarUrl: "http://dummyimage.com/125x100.png/ff4444/ffffff",
  },
  {
    id: 59,
    firstName: "Shani",
    lastName: "Stirton",
    email: "sstirton1m@com.com",
    age: 90,
    address: "Apt 904",
    avatarUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
  },
  {
    id: 60,
    firstName: "Reynard",
    lastName: "Matissoff",
    email: "rmatissoff1n@salon.com",
    age: 55,
    address: "12th Floor",
    avatarUrl: "http://dummyimage.com/197x100.png/cc0000/ffffff",
  },
  {
    id: 61,
    firstName: "Georgina",
    lastName: "Santhouse",
    email: "gsanthouse1o@goo.gl",
    age: 82,
    address: "Apt 1562",
    avatarUrl: "http://dummyimage.com/221x100.png/5fa2dd/ffffff",
  },
  {
    id: 62,
    firstName: "Orville",
    lastName: "Yorath",
    email: "oyorath1p@theatlantic.com",
    age: 34,
    address: "PO Box 94947",
    avatarUrl: "http://dummyimage.com/167x100.png/dddddd/000000",
  },
  {
    id: 63,
    firstName: "Diego",
    lastName: "Barnewille",
    email: "dbarnewille1q@bizjournals.com",
    age: 74,
    address: "Suite 52",
    avatarUrl: "http://dummyimage.com/162x100.png/dddddd/000000",
  },
  {
    id: 64,
    firstName: "Sacha",
    lastName: "Ranvoise",
    email: "sranvoise1r@scribd.com",
    age: 58,
    address: "Apt 1900",
    avatarUrl: "http://dummyimage.com/241x100.png/ff4444/ffffff",
  },
  {
    id: 65,
    firstName: "Lambert",
    lastName: "Huett",
    email: "lhuett1s@amazon.com",
    age: 81,
    address: "Room 1095",
    avatarUrl: "http://dummyimage.com/201x100.png/cc0000/ffffff",
  },
  {
    id: 66,
    firstName: "Davis",
    lastName: "Brakewell",
    email: "dbrakewell1t@japanpost.jp",
    age: 74,
    address: "17th Floor",
    avatarUrl: "http://dummyimage.com/135x100.png/5fa2dd/ffffff",
  },
  {
    id: 67,
    firstName: "Kamila",
    lastName: "Aspinal",
    email: "kaspinal1u@msn.com",
    age: 37,
    address: "PO Box 83030",
    avatarUrl: "http://dummyimage.com/198x100.png/5fa2dd/ffffff",
  },
  {
    id: 68,
    firstName: "Sarita",
    lastName: "Lodwig",
    email: "slodwig1v@reuters.com",
    age: 34,
    address: "Suite 28",
    avatarUrl: "http://dummyimage.com/166x100.png/ff4444/ffffff",
  },
  {
    id: 69,
    firstName: "Ethelyn",
    lastName: "Grouen",
    email: "egrouen1w@java.com",
    age: 30,
    address: "Apt 1029",
    avatarUrl: "http://dummyimage.com/132x100.png/cc0000/ffffff",
  },
  {
    id: 70,
    firstName: "Kaja",
    lastName: "Hallum",
    email: "khallum1x@parallels.com",
    age: 34,
    address: "Suite 51",
    avatarUrl: "http://dummyimage.com/237x100.png/cc0000/ffffff",
  },
  {
    id: 71,
    firstName: "Velvet",
    lastName: "Longdon",
    email: "vlongdon1y@china.com.cn",
    age: 41,
    address: "Apt 355",
    avatarUrl: "http://dummyimage.com/243x100.png/5fa2dd/ffffff",
  },
  {
    id: 72,
    firstName: "Shurlocke",
    lastName: "Sidebotham",
    email: "ssidebotham1z@tuttocitta.it",
    age: 34,
    address: "Apt 807",
    avatarUrl: "http://dummyimage.com/156x100.png/cc0000/ffffff",
  },
  {
    id: 73,
    firstName: "Aurlie",
    lastName: "Griffin",
    email: "agriffin20@spotify.com",
    age: 92,
    address: "Suite 10",
    avatarUrl: "http://dummyimage.com/102x100.png/cc0000/ffffff",
  },
  {
    id: 74,
    firstName: "Hilde",
    lastName: "Bartos",
    email: "hbartos21@t-online.de",
    age: 43,
    address: "13th Floor",
    avatarUrl: "http://dummyimage.com/143x100.png/dddddd/000000",
  },
  {
    id: 75,
    firstName: "Clemmie",
    lastName: "Vasyutin",
    email: "cvasyutin22@epa.gov",
    age: 36,
    address: "Suite 61",
    avatarUrl: "http://dummyimage.com/243x100.png/ff4444/ffffff",
  },
  {
    id: 76,
    firstName: "Findley",
    lastName: "Baldwin",
    email: "fbaldwin23@usda.gov",
    age: 14,
    address: "Room 789",
    avatarUrl: "http://dummyimage.com/145x100.png/5fa2dd/ffffff",
  },
  {
    id: 77,
    firstName: "Fax",
    lastName: "Braemer",
    email: "fbraemer24@stanford.edu",
    age: 68,
    address: "Suite 98",
    avatarUrl: "http://dummyimage.com/230x100.png/dddddd/000000",
  },
  {
    id: 78,
    firstName: "Wynny",
    lastName: "Strode",
    email: "wstrode25@miibeian.gov.cn",
    age: 15,
    address: "Room 1347",
    avatarUrl: "http://dummyimage.com/197x100.png/ff4444/ffffff",
  },
  {
    id: 79,
    firstName: "Juditha",
    lastName: "Tempest",
    email: "jtempest26@live.com",
    age: 95,
    address: "2nd Floor",
    avatarUrl: "http://dummyimage.com/179x100.png/cc0000/ffffff",
  },
  {
    id: 80,
    firstName: "Deedee",
    lastName: "Izatt",
    email: "dizatt27@amazonaws.com",
    age: 61,
    address: "Room 1102",
    avatarUrl: "http://dummyimage.com/132x100.png/cc0000/ffffff",
  },
  {
    id: 81,
    firstName: "Collin",
    lastName: "Eykel",
    email: "ceykel28@springer.com",
    age: 50,
    address: "PO Box 273",
    avatarUrl: "http://dummyimage.com/111x100.png/cc0000/ffffff",
  },
  {
    id: 82,
    firstName: "Beverie",
    lastName: "Witch",
    email: "bwitch29@sciencedaily.com",
    age: 59,
    address: "3rd Floor",
    avatarUrl: "http://dummyimage.com/209x100.png/ff4444/ffffff",
  },
  {
    id: 83,
    firstName: "Bartholomeus",
    lastName: "Ruscoe",
    email: "bruscoe2a@hc360.com",
    age: 60,
    address: "20th Floor",
    avatarUrl: "http://dummyimage.com/185x100.png/5fa2dd/ffffff",
  },
  {
    id: 84,
    firstName: "Felicia",
    lastName: "Bryer",
    email: "fbryer2b@surveymonkey.com",
    age: 23,
    address: "Apt 1340",
    avatarUrl: "http://dummyimage.com/233x100.png/5fa2dd/ffffff",
  },
  {
    id: 85,
    firstName: "Reta",
    lastName: "Garralts",
    email: "rgarralts2c@hubpages.com",
    age: 76,
    address: "PO Box 17594",
    avatarUrl: "http://dummyimage.com/191x100.png/cc0000/ffffff",
  },
  {
    id: 86,
    firstName: "Bride",
    lastName: "Franey",
    email: "bfraney2d@blog.com",
    age: 59,
    address: "Apt 117",
    avatarUrl: "http://dummyimage.com/184x100.png/ff4444/ffffff",
  },
  {
    id: 87,
    firstName: "Lishe",
    lastName: "Brabon",
    email: "lbrabon2e@umn.edu",
    age: 95,
    address: "19th Floor",
    avatarUrl: "http://dummyimage.com/237x100.png/dddddd/000000",
  },
  {
    id: 88,
    firstName: "Kenny",
    lastName: "Poley",
    email: "kpoley2f@europa.eu",
    age: 50,
    address: "Suite 98",
    avatarUrl: "http://dummyimage.com/201x100.png/dddddd/000000",
  },
  {
    id: 89,
    firstName: "Delmore",
    lastName: "Delhanty",
    email: "ddelhanty2g@nps.gov",
    age: 20,
    address: "PO Box 5812",
    avatarUrl: "http://dummyimage.com/184x100.png/cc0000/ffffff",
  },
  {
    id: 90,
    firstName: "Hermann",
    lastName: "Luard",
    email: "hluard2h@seattletimes.com",
    age: 90,
    address: "Apt 232",
    avatarUrl: "http://dummyimage.com/241x100.png/ff4444/ffffff",
  },
  {
    id: 91,
    firstName: "Lammond",
    lastName: "Ollcott",
    email: "lollcott2i@marketwatch.com",
    age: 98,
    address: "Suite 67",
    avatarUrl: "http://dummyimage.com/208x100.png/ff4444/ffffff",
  },
  {
    id: 92,
    firstName: "Dinny",
    lastName: "Brient",
    email: "dbrient2j@columbia.edu",
    age: 52,
    address: "Apt 1402",
    avatarUrl: "http://dummyimage.com/241x100.png/dddddd/000000",
  },
  {
    id: 93,
    firstName: "Laverne",
    lastName: "Scandwright",
    email: "lscandwright2k@netscape.com",
    age: 80,
    address: "Apt 141",
    avatarUrl: "http://dummyimage.com/194x100.png/dddddd/000000",
  },
  {
    id: 94,
    firstName: "Yank",
    lastName: "McCaskell",
    email: "ymccaskell2l@t-online.de",
    age: 77,
    address: "Apt 1285",
    avatarUrl: "http://dummyimage.com/240x100.png/dddddd/000000",
  },
  {
    id: 95,
    firstName: "Fannie",
    lastName: "Petschel",
    email: "fpetschel2m@sciencedirect.com",
    age: 33,
    address: "Suite 8",
    avatarUrl: "http://dummyimage.com/186x100.png/ff4444/ffffff",
  },
  {
    id: 96,
    firstName: "Blisse",
    lastName: "Comelini",
    email: "bcomelini2n@jigsy.com",
    age: 66,
    address: "15th Floor",
    avatarUrl: "http://dummyimage.com/105x100.png/ff4444/ffffff",
  },
  {
    id: 97,
    firstName: "Marshal",
    lastName: "Alyutin",
    email: "malyutin2o@youku.com",
    age: 47,
    address: "Suite 53",
    avatarUrl: "http://dummyimage.com/150x100.png/cc0000/ffffff",
  },
  {
    id: 98,
    firstName: "Zachery",
    lastName: "Esby",
    email: "zesby2p@topsy.com",
    age: 34,
    address: "Suite 64",
    avatarUrl: "http://dummyimage.com/108x100.png/5fa2dd/ffffff",
  },
  {
    id: 99,
    firstName: "Clare",
    lastName: "Garioch",
    email: "cgarioch2q@studiopress.com",
    age: 87,
    address: "19th Floor",
    avatarUrl: "http://dummyimage.com/244x100.png/5fa2dd/ffffff",
  },
  {
    id: 100,
    firstName: "Wayne",
    lastName: "Goodhand",
    email: "wgoodhand2r@ning.com",
    age: 22,
    address: "Apt 995",
    avatarUrl: "http://dummyimage.com/186x100.png/dddddd/000000",
  },
  {
    id: 101,
    firstName: "Ailene",
    lastName: "Ponte",
    email: "aponte2s@blinklist.com",
    age: 37,
    address: "Suite 20",
    avatarUrl: "http://dummyimage.com/116x100.png/5fa2dd/ffffff",
  },
  {
    id: 102,
    firstName: "Pavla",
    lastName: "Exer",
    email: "pexer2t@about.com",
    age: 94,
    address: "PO Box 54839",
    avatarUrl: "http://dummyimage.com/151x100.png/5fa2dd/ffffff",
  },
  {
    id: 103,
    firstName: "Ignazio",
    lastName: "Ducker",
    email: "iducker2u@barnesandnoble.com",
    age: 78,
    address: "16th Floor",
    avatarUrl: "http://dummyimage.com/227x100.png/ff4444/ffffff",
  },
  {
    id: 104,
    firstName: "Tammy",
    lastName: "Bygott",
    email: "tbygott2v@usatoday.com",
    age: 65,
    address: "Room 1788",
    avatarUrl: "http://dummyimage.com/128x100.png/5fa2dd/ffffff",
  },
  {
    id: 105,
    firstName: "Neale",
    lastName: "Harberer",
    email: "nharberer2w@amazon.com",
    age: 24,
    address: "Apt 1380",
    avatarUrl: "http://dummyimage.com/217x100.png/cc0000/ffffff",
  },
  {
    id: 106,
    firstName: "Pen",
    lastName: "Haire",
    email: "phaire2x@parallels.com",
    age: 54,
    address: "PO Box 61292",
    avatarUrl: "http://dummyimage.com/176x100.png/cc0000/ffffff",
  },
  {
    id: 107,
    firstName: "Sileas",
    lastName: "Keaves",
    email: "skeaves2y@blogtalkradio.com",
    age: 44,
    address: "Room 1714",
    avatarUrl: "http://dummyimage.com/132x100.png/5fa2dd/ffffff",
  },
  {
    id: 108,
    firstName: "Dru",
    lastName: "Jurczak",
    email: "djurczak2z@joomla.org",
    age: 47,
    address: "Suite 28",
    avatarUrl: "http://dummyimage.com/182x100.png/ff4444/ffffff",
  },
  {
    id: 109,
    firstName: "Dru",
    lastName: "Jurczak",
    email: "djurczak2z@joomla.org",
    age: 47,
    address: "Suite 28",
    avatarUrl: "http://dummyimage.com/182x100.png/ff4444/ffffff",
  },
  {
    id: 110,
    firstName: "Dru",
    lastName: "Jurczak",
    email: "djurczak2z@joomla.org",
    age: 47,
    address: "Suite 28",
    avatarUrl: "http://dummyimage.com/182x100.png/ff4444/ffffff",
  },
  {
    id: 111,
    firstName: "Dru",
    lastName: "Jurczak",
    email: "djurczak2z@joomla.org",
    age: 47,
    address: "Suite 28",
    avatarUrl: "http://dummyimage.com/182x100.png/ff4444/ffffff",
  },
  {
    id: 112,
    firstName: "Dru",
    lastName: "Jurczak",
    email: "djurczak2z@joomla.org",
    age: 47,
    address: "Suite 28",
    avatarUrl: "http://dummyimage.com/182x100.png/ff4444/ffffff",
  },
];

export const userListMockResponse = () => {
  return mockUsers;
};

export const userDetailMockResponse = (id: number) => {
  const mockResponse = mockUsers.filter((user) => user.id === id)?.pop();
  return mockResponse;
};
